version: '3'
services:
  web:
    image: nginx:alpine
    depends_on:
      - db
      - php
    networks:
      - frontend
    volumes:
      - ./backend:/var/www/html
      - ./nginxconf:/etc/nginx/conf.d
    ports:
    - "80:80"
  db:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        TZ: 'Asia/Shanghai'
        MYSQL_ROOT_PASSWORD: PASSWORD
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_DATABASE: homestead
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    volumes:
      - redis-data:/data
  php:
    image: php:fpm-alpine
    ports:
    - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    networks:
      - frontend
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  frontend:
  backend:
