version: '3'
services:
  web:
    container_name: ${APP_NAME}_web
    image: nginx:alpine
    depends_on:
      - db
      - php
    networks:
      - frontend
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
      - ./nginxconf:/etc/nginx/conf.d
    ports:
    - "${NGINX_PORT}:80"
  db:
    container_name: ${APP_NAME}_db
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "${DB_PORT}:3306"
    restart: always
    environment:
        TZ: 'Asia/Shanghai'
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
  redis:
    container_name: ${APP_NAME}_redis
    image: redis:alpine
    ports:
    - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    command: --requirepass ${REDIS_PASSWORD}
  php:
    container_name: ${APP_NAME}_php
    image: php:fpm-alpine
    ports:
    - "${PHP_PORT}:9000"
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
    networks:
      - frontend
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  frontend:
  backend:
